apiVersion: v1
kind: Secret
metadata:
  name: ado-agent-secret
data:
  AZP_TOKEN: Rk5TMFh4MGpmcFNIU0JQVDRod3ZTeEtCZmJIN3NheDNYZ3c2SWNFVUhQSFUwS0hSMjhWaEpRUUo5OUJDQUNBQUFBQXVQVlF2QUFBU0FaRE9OV1I1Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent-deployment
  labels:
    app: ado-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-agent
  template:
    metadata:
      labels:
        app: ado-agent
    spec:
      containers:
      - name: ado-agent
        image: sturgacr.azurecr.io/adoagent:v1
        env:
          - name: AZP_URL
            value: https://dev.azure.com/mydevopsorg3105
          - name: AZP_POOL
            value: AgentInContainer
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: ado-agent-secret
                key: AZP_TOKEN
        securityContext:
          privileged: true
